

-- 2020-09-28 14:43:48
CREATE TABLE `user`(`id` INTEGER ,`sex` VARCHAR(255) NULL DEFAULT NULL ,`name` VARCHAR(255) NULL DEFAULT NULL ,`money` DECIMAL(19,2) NULL DEFAULT NULL ,PRIMARY KEY ( `id` ));


-- 2020-09-28 15:02:58
ALTER TABLE `user` MODIFY COLUMN`sex` VARCHAR(1) NULL DEFAULT NULL ,MODIFY COLUMN`name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN`email` VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱' ,MODIFY COLUMN`money` DECIMAL(19,2) NULL DEFAULT NULL ,MODIFY COLUMN`id` INTEGER NULL DEFAULT NULL ;


-- 2020-09-28 15:04:42
ALTER TABLE `user` ADD (`email_addr` VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱' );
ALTER TABLE `user` MODIFY COLUMN`sex` VARCHAR(1) NULL DEFAULT NULL ,MODIFY COLUMN`name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN`money` DECIMAL(19,2) NULL DEFAULT NULL ,MODIFY COLUMN`id` INTEGER NULL DEFAULT NULL ;


-- 2020-09-28 15:10:56
ALTER TABLE `user` DROP COLUMN`email`;
ALTER TABLE `user` MODIFY COLUMN`sex` VARCHAR(1) NULL DEFAULT NULL ,MODIFY COLUMN`email_addr` VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱' ,MODIFY COLUMN`name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN`money` DECIMAL(19,2) NULL DEFAULT NULL ,MODIFY COLUMN`id` INTEGER NULL DEFAULT NULL ;


-- 2020-09-28 15:22:15
ALTER TABLE `user` MODIFY COLUMN `sex` VARCHAR(1) NULL DEFAULT NULL ,MODIFY COLUMN `email_addr` VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱' ,MODIFY COLUMN `name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN `money` DECIMAL(19,2) NULL DEFAULT NULL ,MODIFY COLUMN `id` INTEGER NULL DEFAULT NULL ;


-- 2020-09-28 15:25:52
ALTER TABLE `user` ADD (`email` VARCHAR(128) NULL DEFAULT NULL COMMENT '邮箱' );
ALTER TABLE `user` DROP COLUMN `email_addr`;
ALTER TABLE `user` MODIFY COLUMN `sex` VARCHAR(1) NULL DEFAULT NULL ,MODIFY COLUMN `name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN `money` DECIMAL(19,2) NULL DEFAULT NULL ,MODIFY COLUMN `id` INTEGER NULL DEFAULT NULL ;


-- 2020-09-28 15:31:56
ALTER TABLE `user` DROP COLUMN `money`,DROP COLUMN `sex`;
ALTER TABLE `user` MODIFY COLUMN `name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN `email` VARCHAR(128) NULL DEFAULT NULL COMMENT '邮箱' ,MODIFY COLUMN `id` INTEGER NULL DEFAULT NULL ;


-- 2020-09-28 15:32:22
ALTER TABLE `user` ADD (`sex` VARCHAR(1) NULL DEFAULT NULL ,`money` DECIMAL(19,2) NULL DEFAULT NULL );
ALTER TABLE `user` MODIFY COLUMN `name` VARCHAR(255) NULL DEFAULT NULL ,MODIFY COLUMN `email` VARCHAR(128) NULL DEFAULT NULL COMMENT '邮箱' ,MODIFY COLUMN `id` INTEGER NULL DEFAULT NULL ;